### ISSUE TITLE
plainweb can't import files on windows

### ISSUE THREAD

**Issue by p-lleonart** [justplainstuff/plainstack#134]
Hi

I just created a plainweb project and runned `pnpm run dev`.

Error obtained:
![issue plainweb windows](https://github.com/user-attachments/assets/aaa92aac-b71b-46fa-a2e2-fab835903966)

(error: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:')

It seems that plainweb tried to import health.tsx but got the error.

I have:
- windows 10
- node: v20.17.0
- pnpm: v9.10.0

**Comment by joseferben** [comment]
@p-lleonart the latest version of plainweb (now plainstack) should work on windows!
